server:
  port: 8080
logging:
  level:
    root: debug
spring:
  session:
    redis:
      flush-mode: on_save
      namespace: session.foodshare
      cleanup-cron: 0 * * * * *
    store-type: redis
    timeout: 1800
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: 10
        max-idle: 10
        min-idle: 5
    timeout: 1000
  datasource:
    username: root
    password: 6140
    url: jdbc:mariadb://localhost:3306/foodshare?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapping/**.xml
  type-aliases-package: com.asuta.foodshare.entity
  config-location: classpath:mybatis-config.xml

verify-code:
  width: 110
  height: 40
  codeCount: 4
  #maxTone∈[0,255]
  maxTone: 150
  fontName: JetBrains Mono
  #{0,1,2} -> {plain, bold, italic}
  fontStyle: 0
  codeSequence: [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,X,T,U,V,W,X,Y,Z,0,1,2,3,4,5,6,7,8,9]
